package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Annonce generated by hbm2java
 */
public class Annonce implements java.io.Serializable {

	private Integer idAnnonce;
	private Restaurateur restaurateur;
	private Date dateDebutAnnonce;
	private Date dateFinAnnonce;
	private int nbPlaces;
	private int idRestaurant;
	private Set reservations = new HashSet(0);
	private Set creneaus = new HashSet(0);

	public Annonce() {
	}

	public Annonce(Restaurateur restaurateur, Date dateDebutAnnonce, Date dateFinAnnonce, int nbPlaces,
			int idRestaurant) {
		this.restaurateur = restaurateur;
		this.dateDebutAnnonce = dateDebutAnnonce;
		this.dateFinAnnonce = dateFinAnnonce;
		this.nbPlaces = nbPlaces;
		this.idRestaurant = idRestaurant;
	}

	public Annonce(Restaurateur restaurateur, Date dateDebutAnnonce, Date dateFinAnnonce, int nbPlaces,
			int idRestaurant, Set reservations, Set creneaus) {
		this.restaurateur = restaurateur;
		this.dateDebutAnnonce = dateDebutAnnonce;
		this.dateFinAnnonce = dateFinAnnonce;
		this.nbPlaces = nbPlaces;
		this.idRestaurant = idRestaurant;
		this.reservations = reservations;
		this.creneaus = creneaus;
	}

	public Integer getIdAnnonce() {
		return this.idAnnonce;
	}

	public void setIdAnnonce(Integer idAnnonce) {
		this.idAnnonce = idAnnonce;
	}

	public Restaurateur getRestaurateur() {
		return this.restaurateur;
	}

	public void setRestaurateur(Restaurateur restaurateur) {
		this.restaurateur = restaurateur;
	}

	public Date getDateDebutAnnonce() {
		return this.dateDebutAnnonce;
	}

	public void setDateDebutAnnonce(Date dateDebutAnnonce) {
		this.dateDebutAnnonce = dateDebutAnnonce;
	}

	public Date getDateFinAnnonce() {
		return this.dateFinAnnonce;
	}

	public void setDateFinAnnonce(Date dateFinAnnonce) {
		this.dateFinAnnonce = dateFinAnnonce;
	}

	public int getNbPlaces() {
		return this.nbPlaces;
	}

	public void setNbPlaces(int nbPlaces) {
		this.nbPlaces = nbPlaces;
	}

	public int getIdRestaurant() {
		return this.idRestaurant;
	}

	public void setIdRestaurant(int idRestaurant) {
		this.idRestaurant = idRestaurant;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

	public Set getCreneaus() {
		return this.creneaus;
	}

	public void setCreneaus(Set creneaus) {
		this.creneaus = creneaus;
	}

}
