package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie implements java.io.Serializable 
{
	private Integer idCategorie;
	private String nomCatagorie;
	private Set restaurants = new HashSet(0);

	public Categorie() {
	}

	public Categorie(String nomCatagorie) {
		this.nomCatagorie = nomCatagorie;
	}

	public Categorie(String nomCatagorie, Set restaurants) {
		this.nomCatagorie = nomCatagorie;
		this.restaurants = restaurants;
	}

	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	public String getNomCatagorie() {
		return this.nomCatagorie;
	}

	public void setNomCatagorie(String nomCatagorie) {
		this.nomCatagorie = nomCatagorie;
	}

	public Set getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set restaurants) {
		this.restaurants = restaurants;
	}

}
