package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer idClient;
	private Utilisateur utilisateur;
	private Ville ville;
	private Set reservations = new HashSet(0);

	public Client() {
	}

	public Client(Utilisateur utilisateur, Ville ville) {
		this.utilisateur = utilisateur;
		this.ville = ville;
	}

	public Client(Utilisateur utilisateur, Ville ville, Set reservations) {
		this.utilisateur = utilisateur;
		this.ville = ville;
		this.reservations = reservations;
	}

	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
