package model_ORM;
import java.util.Date;

/**
 * Creneau generated by hbm2java
 */
public class Creneau implements java.io.Serializable {

	private Integer idCreneau;
	private Annonce annonce;
	private Date heureDebutCreneau;
	private Date heureFinCreneau;

	public Creneau() {
	}

	public Creneau(Annonce annonce, Date heureDebutCreneau, Date heureFinCreneau) {
		this.annonce = annonce;
		this.heureDebutCreneau = heureDebutCreneau;
		this.heureFinCreneau = heureFinCreneau;
	}

	public Integer getIdCreneau() {
		return this.idCreneau;
	}

	public void setIdCreneau(Integer idCreneau) {
		this.idCreneau = idCreneau;
	}

	public Annonce getAnnonce() {
		return this.annonce;
	}

	public void setAnnonce(Annonce annonce) {
		this.annonce = annonce;
	}

	public Date getHeureDebutCreneau() {
		return this.heureDebutCreneau;
	}

	public void setHeureDebutCreneau(Date heureDebutCreneau) {
		this.heureDebutCreneau = heureDebutCreneau;
	}

	public Date getHeureFinCreneau() {
		return this.heureFinCreneau;
	}

	public void setHeureFinCreneau(Date heureFinCreneau) {
		this.heureFinCreneau = heureFinCreneau;
	}

}
