package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Plagefermeture generated by hbm2java
 */
public class Plagefermeture implements java.io.Serializable {

	private Integer idPlageFermeture;
	private String débutPlage;
	private String finPlage;
	private Set restaurants = new HashSet(0);

	public Plagefermeture() {
	}

	public Plagefermeture(String débutPlage, String finPlage) {
		this.débutPlage = débutPlage;
		this.finPlage = finPlage;
	}

	public Plagefermeture(String débutPlage, String finPlage, Set restaurants) {
		this.débutPlage = débutPlage;
		this.finPlage = finPlage;
		this.restaurants = restaurants;
	}

	public Integer getIdPlageFermeture() {
		return this.idPlageFermeture;
	}

	public void setIdPlageFermeture(Integer idPlageFermeture) {
		this.idPlageFermeture = idPlageFermeture;
	}

	public String getDébutPlage() {
		return this.débutPlage;
	}

	public void setDébutPlage(String débutPlage) {
		this.débutPlage = débutPlage;
	}

	public String getFinPlage() {
		return this.finPlage;
	}

	public void setFinPlage(String finPlage) {
		this.finPlage = finPlage;
	}

	public Set getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set restaurants) {
		this.restaurants = restaurants;
	}

}
