package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

/**
 * Plat generated by hbm2java
 */
public class Plat implements java.io.Serializable {

	private Integer idPlat;
	private Menu menu;
	private Restaurant restaurant;
	private String nomPlat;

	public Plat() {
	}

	public Plat(Menu menu, Restaurant restaurant, String nomPlat) {
		this.menu = menu;
		this.restaurant = restaurant;
		this.nomPlat = nomPlat;
	}

	public Integer getIdPlat() {
		return this.idPlat;
	}

	public void setIdPlat(Integer idPlat) {
		this.idPlat = idPlat;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public String getNomPlat() {
		return this.nomPlat;
	}

	public void setNomPlat(String nomPlat) {
		this.nomPlat = nomPlat;
	}

}
