package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurateur generated by hbm2java
 */
public class Restaurateur implements java.io.Serializable {

	private Integer idRestaurateur;
	private Utilisateur utilisateur;
	private Set annonces = new HashSet(0);
	private Set restaurants = new HashSet(0);

	public Restaurateur() {
	}

	public Restaurateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Restaurateur(Utilisateur utilisateur, Set annonces, Set restaurants) {
		this.utilisateur = utilisateur;
		this.annonces = annonces;
		this.restaurants = restaurants;
	}

	public Integer getIdRestaurateur() {
		return this.idRestaurateur;
	}

	public void setIdRestaurateur(Integer idRestaurateur) {
		this.idRestaurateur = idRestaurateur;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Set getAnnonces() {
		return this.annonces;
	}

	public void setAnnonces(Set annonces) {
		this.annonces = annonces;
	}

	public Set getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set restaurants) {
		this.restaurants = restaurants;
	}

}
