package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tpsmoyenrepas generated by hbm2java
 */
public class Tpsmoyenrepas implements java.io.Serializable {

	private Integer idTpsMoyenRepas;
	private String dureeRepas;
	private String dureeEvenement;
	private Set restaurants = new HashSet(0);

	public Tpsmoyenrepas() {
	}

	public Tpsmoyenrepas(String dureeRepas, String dureeEvenement) {
		this.dureeRepas = dureeRepas;
		this.dureeEvenement = dureeEvenement;
	}

	public Tpsmoyenrepas(String dureeRepas, String dureeEvenement, Set restaurants) {
		this.dureeRepas = dureeRepas;
		this.dureeEvenement = dureeEvenement;
		this.restaurants = restaurants;
	}

	public Integer getIdTpsMoyenRepas() {
		return this.idTpsMoyenRepas;
	}

	public void setIdTpsMoyenRepas(Integer idTpsMoyenRepas) {
		this.idTpsMoyenRepas = idTpsMoyenRepas;
	}

	public String getDureeRepas() {
		return this.dureeRepas;
	}

	public void setDureeRepas(String dureeRepas) {
		this.dureeRepas = dureeRepas;
	}

	public String getDureeEvenement() {
		return this.dureeEvenement;
	}

	public void setDureeEvenement(String dureeEvenement) {
		this.dureeEvenement = dureeEvenement;
	}

	public Set getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set restaurants) {
		this.restaurants = restaurants;
	}

}
