package model_ORM;
// Generated 29 janv. 2017 01:16:12 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ville generated by hbm2java
 */
public class Ville implements java.io.Serializable {

	private Integer idVille;
	private String nomVille;
	private String codePostal;
	private Set clients = new HashSet(0);
	private Set restaurants = new HashSet(0);

	public Ville() {
	}

	public Ville(String nomVille, String codePostal) {
		this.nomVille = nomVille;
		this.codePostal = codePostal;
	}

	public Ville(String nomVille, String codePostal, Set clients, Set restaurants) {
		this.nomVille = nomVille;
		this.codePostal = codePostal;
		this.clients = clients;
		this.restaurants = restaurants;
	}

	public Integer getIdVille() {
		return this.idVille;
	}

	public void setIdVille(Integer idVille) {
		this.idVille = idVille;
	}

	public String getNomVille() {
		return this.nomVille;
	}

	public void setNomVille(String nomVille) {
		this.nomVille = nomVille;
	}

	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

	public Set getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set restaurants) {
		this.restaurants = restaurants;
	}

}
